[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    courses: Для тестов, связанных с курсами.
    dashboard: Маркировка для тестов, связанных с рабочей панелью.
    regression: Маркировка для регрессионных тестов.
    registration: Запускает все автотесты регистрации.
    authorization: Запускает все автотесты авторизации.