[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Запускает все UI автотесты.
    smoke: Запускает все Smoke автотесты.
    regression: Для регрессионных тестов.
    critical: Запускает все Critical автотесты.
    dashboard: Маркировка для тестов, связанных с рабочей панелью.
    registration: Запускает все автотесты регистрации.
    slow: Запускает все медленные автотесты.
    authorization: Запускает все автотесты авторизации.
    courses: Для тестов, связанных с курсами.